### ISSUE TITLE
Error during Build: Missing BUILD_ID and Prisma Configuration Issue

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [Vsoni27/tanstack-query-zustand-tutorial#1]
### Issue Description:
I encountered an issue while building my project. The build process fails due to a missing BUILD_ID file, and there seems to be a problem with my Prisma configuration. Here are the details:

### Steps to Reproduce:
1. Run `npm start`.
2. Observe the error related to the missing BUILD_ID.

### Expected Behavior:
The build process should complete successfully without any missing files or errors.

### Actual Behavior:
The build fails, and the console displays an error related to the BUILD_ID.

**Comment by Vsoni27** [comment]
Fixed!!
 - Run `npm i` to install all dependencies.
 - Create .env file and paste `DATABASE_URL=mysql://USER:PASSWORD@HOST:PORT/DATABASE`, then replace USER, PASSWORD, HOST(localhost), PORT(3306), DATABASE with your own.
 - Run `npx prisma migrate dev --name init`.
 - Finally run `npm run build` and then `npm start`.

Also this project is just a demo for Zustand and TanStack Query, not a complete project.
BTW thanks for reviewing 🙂!
